version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - rm -rf build
      - BUILD_MEMORY=8g
      - npm run build:$BUILD_ENV
  post_build:
    commands:
      - echo Build completed on `date`
      - echo removing node_modules
      - rm -rf node_modules
artifacts:
  files:
    - '**/*'
